[package]
name = "inventory_service_infra"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
# Async traits
async-trait = { workspace = true }

# Database
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-rustls", "macros", "bigdecimal"] }

# Shared crates
shared_db = { workspace = true }
shared_error = { workspace = true }

# Internal crates
inventory_service_core = { workspace = true }

# Other
uuid = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
# Test dependencies
fake = { workspace = true }
mockall = { workspace = true }
proptest = { workspace = true }
tokio-test = "0.4"

[lib]
name = "inventory_service_infra"
path = "src/lib.rs"
